---
title: 'Tidy Tuesday #3'
author: "Put your name here"
output: 
  html_document:
    df_print: paged
    code_download: true
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
library(tidyverse)     # for graphing and data cleaning
library(lubridate)     # for date manipulation
library(ggthemes)      # for even more plotting themes
library(maps)          
library(ggmap)         
library(ggthemes)
theme_set(theme_minimal()) # My favorite ggplot() theme :)

```

## Data choice 1: Freedom Data

```{r}
# Read in the data

  freedom <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-22/freedom.csv')

# If the code above gives an error, uncomment the code below and use it instead. 
# You will need to install the tidytuesdayR package first.

# library(tidytuesdayR)
# 
# tuesdata <- tidytuesdayR::tt_load('2022-02-22')
# tuesdata <- tidytuesdayR::tt_load(2022, week = 8)
# 
# freedom <- tuesdata$freedom
```

This week's data is about civil freedoms around the world. Read more about it, including definitions of variables, [here](https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-02-22/readme.md). 

```{r, fig.alt = "Map showing the changes in the Civil Liberties index according to the Freedom House organization. Countries are highlighted according to whether they are considered \"Developed\" or \"Less Developed\". Most countries show improvement or merely stagnation, yet the US and Russia are notable on the decline in Civil Liberties."}
world_map <- map_data("world")
  
freedom %>% 
  mutate(country2 = ifelse(country == "United States of America", "USA",ifelse(country == "Russian Federation","Russia",ifelse(country == "Bolivia (Plurinational State of)","Bolivia",ifelse(country == "Democratic People's Republic of Korea","North Korea",ifelse(country == "Republic of Korea","South Korea",ifelse(country == "Lao People's Democratic Republic","Laos",ifelse(country == "Syrian Arab Republic","Syria",ifelse(country == "United Kingdom of Great Britain and Northern Ireland","UK",ifelse(country == "Iran (Islamic Republic of)","Iran",ifelse(country == "United Republic of Tanzania","Tanzania",ifelse(country == "Congo","Republic of Congo",ifelse(country == "Viet Nam","Vietnam",country))))))))))))) %>% 
  #I've re-assigned many country names to match the world_map data. Not really sure how to organize this code any better, since starting a new line for each ifelse statement doesn't align the way I would want it. I've resigned this chunk of code to look horrible.
  group_by(country2) %>% 
  summarize(CL_diff = CL[which.max(year)] - CL[which.min(year)], ldc = ifelse(max(is_ldc) == 0,"Developed","Least Developed")) %>% 
  #Above I calculate the change in the CL level in 2020 from 1995, and als0 relabel the more Least Developed Country Variable into something more useful.
  ggplot() +
    geom_map(map = world_map,
             aes(map_id = country2,
                 fill = factor((CL_diff)),
                 color = factor(ldc))) +
  #I made the fill and color variables factors so it wouldn't give me unecessary continuous scales.
  scale_fill_viridis_d() +
  expand_limits(x = world_map$long, y = world_map$lat) + 
  theme_map() +
  theme(legend.background = element_blank()) +
  labs(title = "How have the levels of civil liberty changed around the world?",
       color = "Development Classification",
       fill = "Change in Civil Liberty",
       caption = str_wrap("The Freedom House organization's freedom index rates countries' civil liberties from 1 to 7, with 1 being the highest quality. This map shows the change in that value from 1995 to 2020. Each country's \"Development Index\" is assigned according to that data given by Freedom House."))
```

