---
title: 'Tidy Tuesday #4'
author: "Put your name here"
output: 
  html_document:
    df_print: paged
    code_download: true
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
library(tidyverse)     # for graphing and data cleaning
library(lubridate)     # for date manipulation
library(ggthemes)      # for even more plotting themes
library(plotly)        # for the ggplotly() - basic interactivity
library(gganimate)     # for adding animation layers to ggplots
library(gifski)        # for creating the gif (don't need to load this library every time,but need it installed)
library(transformr)    # for "tweening" (gganimate)
library(shiny)
library(scales)
theme_set(theme_minimal()) # My favorite ggplot() theme :)
```

## Data choice 1: Baby Names

```{r}
# Read in the data

# Or read in the data manually

babynames <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-22/babynames.csv')


# If the code above gives an error, uncomment the code below and use it instead. 
# You will need to install the tidytuesdayR package first.

# library(tidytuesdayR)
# 
# tuesdata <- tidytuesdayR::tt_load('2022-03-22')
# tuesdata <- tidytuesdayR::tt_load(2022, week = 12)
# 
# babynames <- tuesdata$babynames
```



What names were most popular among people born after 1880 as time went on?
```{r, fig.alt = "Baby names used are shown as time progresses from 1880 to 2017. Mary and John are among the most common names over a large span of time."}
  top_names <- babynames %>% 
    group_by(year) %>% 
      filter(year %in% seq(1880, 2017)) %>%
      group_by(name, year) %>% 
      summarize(count = sum(n)) %>%
      group_by(name) %>% 
      mutate(total = cumsum(count)) %>% 
  #Here I totaled up the cumulative babies with a given name
      group_by(year) %>% 
      top_n(n = 10, wt = total) %>%
      arrange(year) %>% 
      arrange(total, .desc = TRUE,.by_group = TRUE) %>% 
      mutate(rank = 1:n()) %>%
  #Adding the rank allows me to plot whichever the highest value is on the top of the graph even when it changes names.
  ggplot(aes(x = total,
             y = factor(rank),
             fill = name,
             group = name)) +
    geom_col() +
    geom_text(aes(label = name)) +
  labs(fill = NULL, 
       title = "Top 10 names by use since 1880",
       subtitle = "Year: {closest_state}",
       x = NULL,
       y = NULL,
       group = NULL) +
  transition_states(year) +
  theme(legend.position = "none",
        axis.text.y = element_blank()) +
  scale_x_continuous(labels = scales::comma)
#Overriding scientific notation

animate(top_names, nframes = 1000, duration = 10)
anim_save("top_names.gif")
```


